// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.RhymingWords
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("word")]
        public string Word { get; set; }

        [JsonProperty("rhymeCount")]
        public long RhymeCount { get; set; }

        [JsonProperty("rhymes")]
        public Rhyme[] Rhymes { get; set; }
    }

    public partial class Rhyme
    {
        [JsonProperty("score")]
        public long Score { get; set; }

        [JsonProperty("pron")]
        public string Pron { get; set; }

        [JsonProperty("word")]
        public string Word { get; set; }
    }
}
